apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: try
  region: ap-south-1

nodeGroups:
  - name: ng-1
    instanceType: t3.large
    desiredCapacity: 2
    
  - name: ng-2
    instanceType: t3.large
    desiredCapacity: 2
   
