apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  namespace: poc
  name: read-pod-deployment
subjects:
-  kind: User
   name: myuser
   apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: read-only
  apiGroup: rbac.authorization.k8s.io